### ISSUE TITLE
Make the sniffer-paths configurable

### ISSUE THREAD

**Issue by svommer** [project-nos/spryker-twig-cs#1]
Hello,

i would suggest, you make the paths in `src/Nos/Yves/TwigCodeSniffer/TwigCodeSnifferConfig.php` configurable via a config or use the current `KernelConstants::PROJECT_NAMESPACES`

**Comment by athopen** [comment]
@svommer Thanks for your feature request. This tool now uses all configured project namespaces in order to generate the appropriate theme paths. These changes are already part of the newest release -> https://github.com/project-nos/spryker-twig-code-sniffer/releases/tag/v1.1.0
