### ISSUE TITLE
Incompatible with vincentlanglet/twig-cs-fixer > 2.0.0

### ISSUE THREAD

**Issue by ynnoig** [project-nos/spryker-twig-cs#4]
ArgumentCountError - Too few arguments to function TwigCsFixer\Report\Reporter\TextReporter::display(), 3 passed in /home/project/actions-runner/_work/project/vendor/project-nos/spryker-twig-code-sniffer/src/Nos/Shared/TwigCodeSniffer/Runner/Runner.php on line 137 and exactly 4 expected in ...vendor/vincentlanglet/twig-cs-fixer/src/Report/Reporter/TextReporter.php::26

The fourth parameter was introduced in version 2.1.0 (https://github.com/VincentLanglet/Twig-CS-Fixer/compare/2.0.0...2.1.0)

**Comment by athopen** [comment]
Thanks @ynnoig for your issue report. I will create a new Release ASAP and lock the version to 2.0.

**Comment by athopen** [comment]
@ynnoig i locked the version to 2.0.x in the newest release -> https://packagist.org/packages/project-nos/spryker-twig-code-sniffer#v1.1.1
